# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e58d9398e790eecf077badd066da1d91f7b9eda013a5ba676b3e8d9f2c316c91b752e1ce138e5782f763f9caf7de0cc4047455dd5d095ebf9029ebac116d583

test:
  secret_key_base: 950dee0a32fae2280441d69404576e26fb44efcf3ae31ab53ef80d432a9abe88f0b3f901a9efdfa9aec15b298808bc6de2254b6957728a5abaefd5834102e21f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
